name: gpu-sound-codia
on:
  push:
    branches:
      - main
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  APP_ID: gpu-sound-codia
  RUN_REGION: asia-southeast1
  SA_KEY_JSON: ${{ secrets.GCP_SA_KEY_JSON }}
  
jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'deploy to FE-FO')"
    steps:
      - uses: actions/checkout@v2
      - id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY_JSON }}'
      - name: Build
        run: gcloud builds submit --tag gcr.io/$PROJECT_ID/$APP_ID:$GITHUB_SHA --project=$PROJECT_ID .